### PR TITLE
Remove sickle_ui dependency

### PR DESCRIPTION
**Pull request by rudderbucky**
This PR removes the sickle_ui dependency

### CODE REVIEW

**Review by UkoeHB — CHANGES_REQUESTED** [review]
Stuff to also remove (scaffold):
- Material icon assets
- `theme_colors.rs`
- `theme_spacing.rs`
- `typography.rs`
- `icons.rs`

Ultimately, `sickle_macros` needs to be removed. But extracting that from the theming framework will be some work. Similarly, most of `ui_builder.rs` and `theme.rs` (scaffold) needs to be removed, but will take some work. Can leave those for a different PR/commits.

**Comment by UkoeHB** [comment]
Also, `drag/drop/resize/scroll_interaction.rs` can be removed. They are not currently used in this crate (although I may resurrect them in the future).

**Comment by UkoeHB** [comment]
If you move `sickle/assets/fonts` to `src/builtin/assets/fonts` then it looks like we can remove the `src/sickle` module (might need to add plugin stuff to `src/sickle_ext/plugin.rs`). Move `src/sickle_ext/default_assets.rs` to `src/builtin/assets/fonts`.

**Comment by eidloi** [comment]
> Ultimately, `sickle_macros` needs to be removed. But extracting that from the theming framework will be some work. Similarly, most of `ui_builder.rs` and `theme.rs` (scaffold) needs to be removed, but will take some work. Can leave those for a different PR/commits.

you don't need the `event_handler` from the macros for sure and you can probably just remove the `ui_context` and `default_theme` since you aren't using it I think. 

As for the `style_command`, it generates about 12kloc if I remember correctly and is the backbone of managing the styles (it generates all the style commands and their implementations). You can probably remove the interactive / animated parts if you have a different driver and port the rest to 0.15 in a new crate (unless you have a better solution to bind the values).

Ping me if you need help with any of that.

**Comment by UkoeHB** [comment]
> As for the style_command, it generates about 12kloc if I remember correctly and is the backbone of managing the styles (it generates all the style commands and their implementations). You can probably remove the interactive / animated parts if you have a different driver and port the rest to 0.15 in a new crate (unless you have a better solution to bind the values).

I don't mind keeping the core `style_command` (minus interactive/animations). It's already built-out, working, and tightly scoped, so maintenance should be pretty low.

**Pull request merged**
